title: José Miguel Horcas Aguilera
author: José Miguel Horcas
email: horcas@uma.es
description: Personal website
baseurl: "" # Empty Leave it empty if it's for a github.io domain
url: "https://jmhorcas.github.io"

# Markdown configuration
markdown: kramdown

collections:
  projects: # English
    output: true
    permalink: /projects/:path/
  projects_es: # Spanish
    output: true
    permalink: /es/projects/:path/
  publications: # English
    output: true
    permalink: /publications/:path/
  publications_es: # Spanish
    output: true
    permalink: /es/publications/:path/

defaults:
  # Configuración para Proyectos en Inglés
  - scope:
      path: "" # Archivos en la raíz
      type: "projects" # Todos los archivos en la colección 'projects'
    values:
      layout: "default"
      lang: "en"
  # Configuración para Proyectos en Español
  - scope:
      path: ""
      type: "projects_es" # Todos los archivos en la colección 'projects_es'
    values:
      layout: "default"
      lang: "es"
  - scope:
      path: ""
      type: "publications" # Para las publicaciones también
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: ""
      type: "publications_es"
    values:
      layout: "default"
      lang: "es"